name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  code-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.code.lines.svg
          base: ""
          plugin_code: yes
          plugin_code_lines: 12

  followup:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.followup.svg
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user

  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.leetcode.svg
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: Debug_coder

  notable:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.notable.contributions.svg
          base: ""
          plugin_notable: yes

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact

  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.languages.activity.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%

  discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.discussions.svg
          base: ""
          plugin_discussions: yes

  reactions:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.reactions.svg
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_display: top
