name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Runs every day
  workflow_dispatch:             # Also allow manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shristirajpoot
          base: header, repositories
          plugin_followup: yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_languages: yes
          plugin_reactions: yes
          plugin_discussions: yes
          plugin_code: yes
          plugin_leetcode: yes
          plugin_leetcode_user: Debug_coder
          plugin_codeforces: yes
          plugin_codeforces_user: Greedy_Coder1
