name: 📊 Generate Metrics

on:
  # Runs every day at 12AM IST
  schedule:
    - cron: '30 18 * * *'  # UTC 18:30 = 00:00 IST
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: 📊 Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shristirajpoot
          config_timezone: Asia/Kolkata

          # Output mode to save individual SVGs to the repo
          filename: metrics.plugin.base.svg

          # Enable desired plugins
          base: header, repositories
          plugin_lines: yes
          plugin_followup: yes
          plugin_achievements: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 6
          plugin_reactions: yes
          plugin_discussions: yes
          plugin_notable: yes
          plugin_notable_repositories: 2
          plugin_leetcode: yes
          plugin_leetcode_user: Debug_coder
          plugin_leetcode_sections: solved
          plugin_leetcode_limit_skills: 20
          plugin_leetcode_limit_recent: 2

          # Enable SVG output for each plugin separately
          output_action: commit
          output_action_filename: |
            metrics.plugin.code.lines.svg
            metrics.plugin.followup.svg
            metrics.plugin.leetcode.svg
            metrics.plugin.notable.contributions.svg
            metrics.plugin.achievements.svg
            metrics.plugin.languages.activity.svg
            metrics.plugin.discussions.svg
            metrics.plugin.reactions.svg
