name: GitHub Metrics

on:
  # Runs automatically every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Trigger on push to main (optional)
  push:
    branches: ["main"]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Path to output file
          filename: metrics.full.svg
          # GitHub token stored in repo secrets
          token: ${{ secrets.GH_TOKEN }}

          # Core settings
          user: Shristirajpoot
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          plugin_code: yes
          plugin_code_lines: 12

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: metrics
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_notable: yes

          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_display: top

          plugin_discussions: yes

          plugin_leetcode: yes
          plugin_leetcode_user: Debug_coder

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons

          plugin_traffic: yes
