name: GitHub Metrics

on:
  schedule: [{cron: "0 * * * *"}]  # Every hour
  push: {branches: ["main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_followup: yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_languages: yes
          plugin_reactions: yes
          plugin_discussions: yes
          plugin_code: yes
          plugin_leetcode: yes
          plugin_leetcode_user: ${{ secrets.LEETCODE_USER }}
